// SPDX-FileCopyrightText: 2026 roolrz
// SPDX-License-Identifier: Apache-2.0
#define _POSIX_C_SOURCE 200809L
#include "hyper_network.h"
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

static volatile sig_atomic_t stopping;
static void stop_signal(int signal)
{
	(void)signal;
	stopping = 1;
}
int main(int argc, char **argv)
{
	unsigned ids[128];
	unsigned count = 0;
	char targets[128][32];
	char networks[128][32], macs[128][18];
	char line[160];
	pid_t children[128] = {0};
	if (argc != 2)
		return 2;
	FILE *file = fopen(argv[1], "r");
	if (!file)
		return 1;
	while (fgets(line, sizeof(line), file)) {
		char extra;
		if (count == 128 || !strchr(line, '\n') ||
		    sscanf(line, "%u %31s %31s %17s %c", &ids[count],
			   targets[count], networks[count], macs[count],
			   &extra) != 4 ||
		    ids[count] >= 128)
			return 1;
		/* The plan is generated by hyper-volumes, but reject
		 * executable/path input. */
		if (strcmp(targets[count], "-") &&
		    (strlen(targets[count]) != 20 ||
		     strncmp(targets[count], "naa.", 4)))
			return 1;
		for (unsigned j = 4; strcmp(targets[count], "-") && j < 20; ++j)
			if (!strchr("0123456789abcdef", targets[count][j]))
				return 1;
		unsigned char mac[6];
		int network = strcmp(networks[count], "-") != 0;
		if ((network &&
		     (hyper_mac_parse(macs[count], mac) || !ids[count])) ||
		    (!network && (strcmp(macs[count], "-") ||
				  !strcmp(targets[count], "-"))))
			return 1;
		for (unsigned j = 0; j < count; ++j)
			if (ids[j] == ids[count] ||
			    (strcmp(targets[count], "-") &&
			     !strcmp(targets[j], targets[count])) ||
			    (network && !strcmp(macs[j], macs[count])))
				return 1;
		++count;
	}
	if (ferror(file) || !count)
		return 1;
	fclose(file);
	struct sigaction action = {.sa_handler = stop_signal};
	sigemptyset(&action.sa_mask);
	if (sigaction(SIGTERM, &action, NULL) ||
	    sigaction(SIGINT, &action, NULL))
		return 1;
	unsigned live = 0;
	int failed = 0;
	for (unsigned i = 0; i < count; ++i) {
		if (stopping)
			break;
		pid_t pid = fork();
		if (pid < 0) {
			failed = 1;
			stopping = 1;
			break;
		}
		if (!pid) {
			char memory[64];
			char control[64];
			char notification[64], net_notification[64];
			snprintf(memory, sizeof(memory), "/dev/hyper-memory-%u",
				 ids[i]);
			snprintf(control, sizeof(control),
				 "/dev/hyper-io-control-%u", ids[i]);
			snprintf(notification, sizeof(notification),
				 "/dev/hyper-io-notification-%u", ids[i]);
			snprintf(net_notification, sizeof(net_notification),
				 "/dev/hyper-io-notification-%u-net", ids[i]);
			execl("/usr/bin/hyper-io-service", "hyper-io-service",
			      memory, targets[i], control, notification,
			      networks[i], macs[i], net_notification,
			      (char *)NULL);
			_exit(127);
		}
		children[i] = pid;
		++live;
	}
	int signalled = 0;
	while (live) {
		if (stopping && !signalled) {
			for (unsigned i = 0; i < count; ++i)
				if (children[i])
					kill(children[i], SIGTERM);
			signalled = 1;
		}
		int status;
		pid_t pid = waitpid(-1, &status, 0);
		if (pid < 0) {
			if (errno == EINTR)
				continue;
			return 1;
		}
		for (unsigned i = 0; i < count; ++i)
			if (children[i] == pid) {
				children[i] = 0;
				--live;
				break;
			}
		if (!WIFEXITED(status) || WEXITSTATUS(status)) {
			failed = 1;
			stopping = 1;
		}
		/* A normally closed control endpoint retires only that client.
		 * The other services continue; RELEASE_MEMORY supports reuse
		 * without closing it. */
	}
	return failed ? 1 : 0;
}
